const assert = require("node:assert/strict");
const path = require("node:path");

exports.verify = async ({ browser, stub, root, out }) => {
  let checks = 0;
  const errors = [];
  const check = (condition, label) => { assert.ok(condition, label); checks++; };
  for (const viewport of [{width:1400,height:900},{width:1024,height:768},{width:800,height:600}]) {
    const page = await browser.newPage({ viewport });
    page.on("pageerror", e => errors.push(String(e)));
    page.on("console", m => { if (m.type() === "error") errors.push(m.text()); });
    // Repeat metadata to exercise virtualization, not 5,000 disk files.
    await page.addInitScript(stub.replace("length: 1240", "length: 5000"));
    await page.goto(`file://${path.join(root,"ui/index.html")}`);
    await page.waitForSelector('.keyrow[data-action="grid"]', { state: "attached" });
    await page.click("#open");
    await page.waitForFunction(() => document.body.getAttribute("aria-busy") === "false");
    await page.click('[data-command="grid"]');
    await page.waitForSelector(".grid-card canvas");
    check(await page.locator(".grid-card").count() < 100, "Grid renders a bounded virtual window");
    check(await page.locator('#ring .shown').count() === 0, "Grid releases viewer images");
    await page.locator('[data-index="0"]').click();
    await page.locator('[data-index="2"]').click();
    check((await page.locator("#selection-count").innerText()).startsWith("2 "), "Clicks accumulate selection");
    await page.locator('[data-index="4"]').click({ modifiers:["Shift"] });
    check((await page.locator("#selection-count").innerText()).startsWith("4 "), "Shift adds an interval");
    await page.click('[data-command="star4"]');
    await page.waitForFunction(() => document.body.getAttribute("aria-busy") === "false");
    check(await page.evaluate(() => [0,2,3,4].every(i => window.__preview.marks[i].rating === 4) && window.__preview.marks[1].rating === 0), "Rating updates only selected indices");
    await page.keyboard.press("Control+z");
    await page.waitForFunction(() => window.__preview.marks[0].rating === 0);
    check(await page.evaluate(() => [0,2,3,4].every(i => window.__preview.marks[i].rating === 0)), "Undo reverses the whole batch");
    await page.keyboard.press("Control+Shift+z");
    await page.waitForFunction(() => window.__preview.marks[0].rating === 4);
    await page.click('nav [data-command="collections"]');
    await page.click('#collections-sidebar [data-command="newCollection"]');
    await page.fill("#collection-name","Selecionadas");
    await page.click("#collection-create");
    await page.locator("#move-list button").first().click();
    await page.waitForFunction(() => document.body.getAttribute("aria-busy") === "false");
    check(await page.evaluate(() => [0,2,3,4].every(i => window.__preview.assigned[i] === 0)), "New collection applies to the selected batch");
    await page.click('#collections-sidebar [data-command="collections"]');
    await page.waitForSelector(".grid-card canvas");
    await page.screenshot({path:path.join(out,`grid-${viewport.width}x${viewport.height}-selection.png`)});
    await page.click('[data-command="applyXmp"]');
    await page.waitForSelector("#apply:not([hidden])");
    check((await page.locator("#apply-scope").innerText()).includes("4 fotos selecionadas"), "Review identifies the selected scope");
    await page.screenshot({path:path.join(out,`grid-${viewport.width}x${viewport.height}-xmp-review.png`)});
    await page.click("#apply-go");
    await page.waitForSelector("#report:not([hidden])");
    check(await page.evaluate(() => window.__preview.calls.filter(c => c.name === "apply").at(-1).args.operation === "xmp"), "XMP button requests only XMP");
    check(await page.evaluate(() => window.__preview.assigned[0] === 0), "XMP leaves organization pending");
    await page.keyboard.press("Escape");
    await page.click('[data-command="applyOrganization"]');
    await page.waitForSelector("#apply:not([hidden])");
    await page.click("#apply-go");
    await page.waitForSelector("#report:not([hidden])");
    check(await page.evaluate(() => window.__preview.calls.filter(c => c.name === "apply").at(-1).args.operation === "organization"), "Organization requests only moves");
    await page.keyboard.press("Escape");
    await page.click('[data-command="clearSelection"]');
    check(await page.locator('[data-command="applyXmp"]').isDisabled(), "Empty selection disables batch writes");
    await page.locator('[data-index="0"]').dblclick();
    check(await page.locator("#grid-view").isHidden(), "Double-click opens the individual viewer");
    await page.keyboard.press("e");
    await page.waitForSelector(".grid-card");
    check((await page.locator("#selection-count").innerText()).startsWith("1 "), "View switching preserves selection");
    await page.locator("#grid-scroll").focus();
    await page.keyboard.press("Control+a");
    check((await page.locator("#selection-count").innerText()).startsWith("5000 "), "Select-all includes unrendered photos");
    await page.locator("#grid-scroll").evaluate(node => node.scrollTop = node.scrollHeight - node.clientHeight);
    await page.waitForSelector('[data-index="4999"]');
    check(await page.locator(".grid-card").count() < 100, "Scrolling does not accumulate cards");
    check(await page.locator(".grid-card canvas").count() < 100, "Decoded miniature canvases remain bounded");
    await page.keyboard.press("Escape");
    await page.locator('[data-index="4999"]').click();
    await page.locator("#grid-scroll").focus();
    await page.keyboard.press("Control+Space");
    check((await page.locator("#selection-count").innerText()).startsWith("0 "), "Ctrl+Space toggles the focused photo");
    await page.click('nav [data-command="filter"]');
    await page.locator("#filter-list button").nth(5).click();
    check(await page.locator("#no-results").isVisible(), "Empty filtered grid offers recovery");
    await page.click('[data-command="clearFilter"]');
    await page.waitForSelector(".grid-card");
    const outside = await page.evaluate(() => [...document.querySelectorAll(".bar button, .grid-toolbar button, .grid-apply button")].filter(n => n.getClientRects().length).filter(n => { const b=n.getBoundingClientRect();return b.left<0||b.right>innerWidth+1||b.bottom>innerHeight+1; }).map(n=>n.textContent));
    check(!outside.length, `Controls fit ${viewport.width}px: ${outside}`);
    await page.close();
  }
  assert.deepEqual(errors, [], "Grid has no browser errors");
  console.log(`${checks} grid assertions passed, including 5,000-photo virtualization.`);
};
